development: &development
  STRIPE_SECRET_KEY: yabadabadooo-secret
  STRIPE_PUBLISHABLE_KEY: yabadabadooo

production: &production
  STRIPE_SECRET_KEY: yabadabadooo-secret-live
  STRIPE_PUBLISHABLE_KEY: yabadabadooo